export const ADMIN_LOGGED_IN = 'ADMIN_LOGGED_IN';
export const ADMIN_LOGGED_OUT = 'ADMIN_LOGGED_OUT';

export const STUDENT_LOGGED_IN = 'STUDENT_LOGGED_IN';
export const STUDENT_LOGGED_OUT = 'STUDENT_LOGGED_OUT';

export const TEACHER_LOGGED_IN = 'TEACHER_LOGGED_IN';
export const TEACHER_LOGGED_OUT = 'TEACHER_LOGGED_OUT';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const ADMIN_ADDED_GROUP = 'ADMIN_ADDED_GROUP';
export const ADMIN_ADDED_STUDENT = 'ADMIN_ADDED_STUDENT';
export const ADMIN_ADDED_TEACHER = 'ADMIN_ADDED_TEACHER';
export const ADMIN_ADDED_LESSON = 'ADMIN_ADDED_LESSON';