export const ADMIN_LOGGED_IN = 'ADMIN_LOGGED_IN';
export const ADMIN_LOGGED_OUT = 'ADMIN_LOGGED_OUT';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const ADMIN_ADDED_GROUP = 'ADMIN_ADDED_GROUP';
export const ADMIN_ADDED_STUDENT = 'ADMIN_ADDED_STUDENT';